#!/usr/bin/env bash

set -euo pipefail

: "${MODAL_SECRET_NAME:?MODAL_SECRET_NAME is required}"
: "${OBSERVABILITY_ENVIRONMENT:?OBSERVABILITY_ENVIRONMENT is required}"
: "${HOSTNAMES:?HOSTNAMES is required}"
: "${PUBLIC_BASE_URL:?PUBLIC_BASE_URL is required}"
: "${UK_CHAT_EVAL_TOKEN:?UK_CHAT_EVAL_TOKEN is required}"

billing_enabled="${BILLING_ENABLED:-false}"

secret_args=(
  "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY"
  "ANTHROPIC_FAST_MODEL=claude-haiku-4-5"
  "ANTHROPIC_COMPLEX_MODEL=claude-sonnet-4-6"
  "ANTHROPIC_TITLE_MODEL=claude-haiku-4-5"
  "ANTHROPIC_DEFAULT_MODEL=claude-haiku-4-5"
  "UK_CHAT_EVAL_TOKEN=$UK_CHAT_EVAL_TOKEN"
  "POLICYENGINE_UK_DATA_TOKEN=$POLICYENGINE_UK_DATA_TOKEN"
  "HUGGING_FACE_TOKEN=$HUGGING_FACE_TOKEN"
  "DATABASE_URL=$DATABASE_URL"
  "BILLING_ENABLED=$billing_enabled"
  "OBSERVABILITY_ENVIRONMENT=$OBSERVABILITY_ENVIRONMENT"
  "OBSERVABILITY_GOOGLE_CLOUD_PROJECT=$OBSERVABILITY_GOOGLE_CLOUD_PROJECT"
  "OBSERVABILITY_GOOGLE_WORKLOAD_IDENTITY_PROVIDER=$OBSERVABILITY_GOOGLE_WORKLOAD_IDENTITY_PROVIDER"
  "OBSERVABILITY_GOOGLE_SERVICE_ACCOUNT_EMAIL=$OBSERVABILITY_GOOGLE_SERVICE_ACCOUNT_EMAIL"
  "OBSERVABILITY_LOG_DESTINATIONS=$OBSERVABILITY_LOG_DESTINATIONS"
  "HOSTNAMES=$HOSTNAMES"
  "PUBLIC_BASE_URL=$PUBLIC_BASE_URL"
)

if [[ "$billing_enabled" == "true" ]]; then
  : "${SUPABASE_URL:?SUPABASE_URL is required when billing is enabled}"
  : "${SUPABASE_SERVICE_ROLE_KEY:?SUPABASE_SERVICE_ROLE_KEY is required when billing is enabled}"
  : "${STRIPE_SECRET_KEY:?STRIPE_SECRET_KEY is required when billing is enabled}"
  : "${STRIPE_WEBHOOK_SECRET:?STRIPE_WEBHOOK_SECRET is required when billing is enabled}"
  secret_args+=(
    "SUPABASE_URL=$SUPABASE_URL"
    "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY"
    "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY"
    "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET"
  )
fi

modal secret create "$MODAL_SECRET_NAME" "${secret_args[@]}" --force
