"""pre branch conversation schema baseline

Revision ID: 0001
Revises:
Create Date: 2026-08-30 12:56:10.894177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=True),
    sa.Column('share_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_conversations_session_id_unique', 'chat_conversations', ['session_id'], unique=True)
    op.create_index('idx_chat_conversations_share_token', 'chat_conversations', ['share_token'], unique=False)
    op.create_index('ix_conversations_session', 'chat_conversations', ['session_id'], unique=False)
    op.create_index('ix_conversations_updated', 'chat_conversations', ['updated_at'], unique=False)
    op.create_index('ix_conversations_user', 'chat_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_user', table_name='chat_conversations')
    op.drop_index('ix_conversations_updated', table_name='chat_conversations')
    op.drop_index('ix_conversations_session', table_name='chat_conversations')
    op.drop_index('idx_chat_conversations_share_token', table_name='chat_conversations')
    op.drop_index('idx_chat_conversations_session_id_unique', table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
