"""add capability persistence tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-26 14:08:46.133104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_artifacts',
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index('idx_capability_artifacts_conversation', 'capability_artifacts', ['conversation_id'], unique=False)
    op.create_index('idx_capability_artifacts_type', 'capability_artifacts', ['artifact_type'], unique=False)
    op.create_table('capability_call_receipts',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('request_fingerprint', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('idx_capability_call_conversation', 'capability_call_receipts', ['conversation_id'], unique=False)
    op.create_index('idx_capability_call_operation', 'capability_call_receipts', ['operation_id'], unique=False)
    op.create_index('idx_capability_call_turn', 'capability_call_receipts', ['turn_id'], unique=False)
    op.create_table('capability_invocation_traces',
    sa.Column('invocation_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('parent_invocation_id', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('invocation_id')
    )
    op.create_index('idx_capability_trace_conversation_sequence', 'capability_invocation_traces', ['conversation_id', 'sequence'], unique=False)
    op.create_index('idx_capability_trace_identifier', 'capability_invocation_traces', ['identifier'], unique=False)
    op.create_index('idx_capability_trace_parent', 'capability_invocation_traces', ['parent_invocation_id'], unique=False)
    op.create_index('idx_capability_trace_turn', 'capability_invocation_traces', ['turn_id'], unique=False)
    op.create_table('capability_turn_receipts',
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('request_fingerprint', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('public_outcome_json', sa.String(), nullable=True),
    sa.Column('billing_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('turn_id')
    )
    op.create_index('idx_capability_turn_conversation', 'capability_turn_receipts', ['conversation_id'], unique=False)
    op.create_table('waiting_capability_invocations',
    sa.Column('invocation_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('capability_version', sa.String(), nullable=False),
    sa.Column('input_schema_version', sa.String(), nullable=False),
    sa.Column('partial_input_json', sa.String(), nullable=False),
    sa.Column('source_turn_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('invocation_id')
    )
    op.create_index('idx_waiting_capability_conversation', 'waiting_capability_invocations', ['conversation_id'], unique=False)
    op.create_index('idx_waiting_capability_id', 'waiting_capability_invocations', ['capability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_waiting_capability_id', table_name='waiting_capability_invocations')
    op.drop_index('idx_waiting_capability_conversation', table_name='waiting_capability_invocations')
    op.drop_table('waiting_capability_invocations')
    op.drop_index('idx_capability_turn_conversation', table_name='capability_turn_receipts')
    op.drop_table('capability_turn_receipts')
    op.drop_index('idx_capability_trace_turn', table_name='capability_invocation_traces')
    op.drop_index('idx_capability_trace_parent', table_name='capability_invocation_traces')
    op.drop_index('idx_capability_trace_identifier', table_name='capability_invocation_traces')
    op.drop_index('idx_capability_trace_conversation_sequence', table_name='capability_invocation_traces')
    op.drop_table('capability_invocation_traces')
    op.drop_index('idx_capability_call_turn', table_name='capability_call_receipts')
    op.drop_index('idx_capability_call_operation', table_name='capability_call_receipts')
    op.drop_index('idx_capability_call_conversation', table_name='capability_call_receipts')
    op.drop_table('capability_call_receipts')
    op.drop_index('idx_capability_artifacts_type', table_name='capability_artifacts')
    op.drop_index('idx_capability_artifacts_conversation', table_name='capability_artifacts')
    op.drop_table('capability_artifacts')
    # ### end Alembic commands ###
