"""add conversation context persistence

Revision ID: 9526d8c80914
Revises: d97a20592837
Create Date: 2026-08-27 21:45:35.140597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9526d8c80914'
down_revision: Union[str, Sequence[str], None] = 'd97a20592837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_contexts',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_conversation_context_updated', 'conversation_contexts', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_context_updated', table_name='conversation_contexts')
    op.drop_table('conversation_contexts')
    # ### end Alembic commands ###
