"""add invocation debug projections

Revision ID: d97a20592837
Revises: 0002
Create Date: 2026-08-26 15:23:18.061675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97a20592837'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capability_invocation_traces', sa.Column('debug_input_json', sa.String(), nullable=True))
    op.add_column('capability_invocation_traces', sa.Column('debug_output_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capability_invocation_traces', 'debug_output_json')
    op.drop_column('capability_invocation_traces', 'debug_input_json')
    # ### end Alembic commands ###
